#!/bin/bash
echo -e "Best School"  > "\\*\\\\"Best School"\\\\\*$\\?\\*\\*\\*\\*\\*:)"
echo "Best School" > "\\*\\\\"Best School"\\\\\*$\\?\\*\\*\\*\\*\\*:)"
echo -e "Best School" > "\\*\\\\"Best School"\\\\\*$\\?\\*\\*\\*\\*\\*:)"
echo -e Best School School\'\*$\?\*\*\*\*\*:)
